# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: campaignProto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='campaignProto.proto',
  package='Campaign',
  serialized_pb='\n\x13\x63\x61mpaignProto.proto\x12\x08\x43\x61mpaign\">\n\rCampaignParam\x12-\n\x08\x63\x61mpaign\x18\x01 \x03(\x0b\x32\x1b.Campaign.CampaignInfoParam\"j\n\x11\x43\x61mpaignInfoParam\x12\x0e\n\x06\x63\x61mpId\x18\x01 \x02(\t\x12\r\n\x05\x61\x64vId\x18\x02 \x02(\t\x12\t\n\x01w\x18\x03 \x02(\r\x12+\n\x07product\x18\x04 \x03(\x0b\x32\x1a.Campaign.ProductInfoParam\"\\\n\x10ProductInfoParam\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\t\n\x01w\x18\x02 \x02(\r\x12\x0e\n\x06prodId\x18\x03 \x02(\t\x12\r\n\x05\x63\x61tId\x18\x04 \x02(\t\x12\x10\n\x08subCatId\x18\x05 \x02(\t\"\xe4\x01\n\x0b\x43onfigParam\x12\x1b\n\x13time_duration_milli\x18\x01 \x02(\r\x12\x13\n\x0bmax_traffic\x18\x02 \x02(\r\x12\x14\n\x0cmean_traffic\x18\x03 \x02(\r\x12\x1c\n\x14\x62urst_seperation_min\x18\x04 \x02(\r\x12\x1a\n\x12\x62urst_duration_sec\x18\x05 \x02(\r\x12!\n\x19no_traffic_seperation_min\x18\x06 \x02(\r\x12\x1f\n\x17no_traffic_duration_sec\x18\x07 \x02(\r\x12\x0f\n\x07stage_w\x18\x08 \x03(\r')




_CAMPAIGNPARAM = _descriptor.Descriptor(
  name='CampaignParam',
  full_name='Campaign.CampaignParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='campaign', full_name='Campaign.CampaignParam.campaign', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=95,
)


_CAMPAIGNINFOPARAM = _descriptor.Descriptor(
  name='CampaignInfoParam',
  full_name='Campaign.CampaignInfoParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='campId', full_name='Campaign.CampaignInfoParam.campId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='advId', full_name='Campaign.CampaignInfoParam.advId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='Campaign.CampaignInfoParam.w', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product', full_name='Campaign.CampaignInfoParam.product', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=203,
)


_PRODUCTINFOPARAM = _descriptor.Descriptor(
  name='ProductInfoParam',
  full_name='Campaign.ProductInfoParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Campaign.ProductInfoParam.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='Campaign.ProductInfoParam.w', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prodId', full_name='Campaign.ProductInfoParam.prodId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='catId', full_name='Campaign.ProductInfoParam.catId', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subCatId', full_name='Campaign.ProductInfoParam.subCatId', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=205,
  serialized_end=297,
)


_CONFIGPARAM = _descriptor.Descriptor(
  name='ConfigParam',
  full_name='Campaign.ConfigParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_duration_milli', full_name='Campaign.ConfigParam.time_duration_milli', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_traffic', full_name='Campaign.ConfigParam.max_traffic', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_traffic', full_name='Campaign.ConfigParam.mean_traffic', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='burst_seperation_min', full_name='Campaign.ConfigParam.burst_seperation_min', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='burst_duration_sec', full_name='Campaign.ConfigParam.burst_duration_sec', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_traffic_seperation_min', full_name='Campaign.ConfigParam.no_traffic_seperation_min', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_traffic_duration_sec', full_name='Campaign.ConfigParam.no_traffic_duration_sec', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stage_w', full_name='Campaign.ConfigParam.stage_w', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=300,
  serialized_end=528,
)

_CAMPAIGNPARAM.fields_by_name['campaign'].message_type = _CAMPAIGNINFOPARAM
_CAMPAIGNINFOPARAM.fields_by_name['product'].message_type = _PRODUCTINFOPARAM
DESCRIPTOR.message_types_by_name['CampaignParam'] = _CAMPAIGNPARAM
DESCRIPTOR.message_types_by_name['CampaignInfoParam'] = _CAMPAIGNINFOPARAM
DESCRIPTOR.message_types_by_name['ProductInfoParam'] = _PRODUCTINFOPARAM
DESCRIPTOR.message_types_by_name['ConfigParam'] = _CONFIGPARAM

class CampaignParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAMPAIGNPARAM

  # @@protoc_insertion_point(class_scope:Campaign.CampaignParam)

class CampaignInfoParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAMPAIGNINFOPARAM

  # @@protoc_insertion_point(class_scope:Campaign.CampaignInfoParam)

class ProductInfoParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRODUCTINFOPARAM

  # @@protoc_insertion_point(class_scope:Campaign.ProductInfoParam)

class ConfigParam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGPARAM

  # @@protoc_insertion_point(class_scope:Campaign.ConfigParam)


# @@protoc_insertion_point(module_scope)
